<?php

/**
 * Implements hook_help().
 */
function home_subcompany_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.home_subcompany':
      return '<p>' . t('Description of what your module does and how to use it.') . '</p>';
      break;
  }
}

function home_subcompany_theme($existing, $type, $theme, $path) {
  return [
    'home_subcompany' => [
      'variables' => [
        'promo' => NULL,
      ],
    ],
  ];
}