<?php

/**
 * Implements hook_help().
 */
function home_about_help($route_name, \Drupal\Core\Routing\RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.home_about':
      return '<p>' . t('Description of what your module does and how to use it.') . '</p>';
      break;
  }
}

function home_about_theme($existing, $type, $theme, $path) {
  return [
    'home_about' => [
      'variables' => [
        'test'=>'yoho',
        'img_bg'=>NULL,
        'content'=>NULL,
      ],
    ],
  ];
}