<?php

/**
 * @file
 * Primary module hooks for bricc module.
 */

use Drupal\bricc\Entity\BriccCardItem;
use Drupal\bricc\Entity\BriccCategory;
use Drupal\config_pages\Entity\ConfigPages;
use Drupal\Core\Cache\Cache;
use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Render\Element;
use Drupal\Core\Url;
use Drupal\file\Entity\File;
use Drupal\media\Entity\Media;
use Drupal\node\Entity\Node;
use Drupal\user\UserInterface;

/**
 * Implements hook_theme().
 */
function bricc_theme(): array {
  return [
    'bricc_category' => ['render element' => 'elements'],
    'bricc_card_item' => ['render element' => 'elements'],
    'applicant_detail' => [
      'variables' => [
        'detail' => NULL,
      ],
    ],
    'applicant_detail_alt' => [
      'variables' => [
        'detail' => NULL,
        'is_print' => NULL,
      ],
    ],
  ];
}

/**
 * Prepares variables for category templates.
 *
 * Default template: bricc-category.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the category information and
 *   any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_bricc_category(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Prepares variables for card item templates.
 *
 * Default template: bricc-card-item.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the card item information and
 *   any fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_bricc_card_item(array &$variables): void {
  $variables['view_mode'] = $variables['elements']['#view_mode'];
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}

/**
 * Implements hook_user_cancel().
 *
 * @todo Handle content ownership for card items
 */
function bricc_user_cancel($edit, UserInterface $account, $method): void {
  switch ($method) {
    case 'user_cancel_block_unpublish':
      // Unpublish categories.
      $storage = \Drupal::entityTypeManager()->getStorage('bricc_category');
      $bricc_category_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($bricc_category_ids) as $bricc_category) {
        $bricc_category->set('status', FALSE)->save();
      }

      // Unpublish Card Item
      $storageCard = \Drupal::entityTypeManager()->getStorage('bricc_card_item');
      $bricc_card_ids = $storageCard->getQuery()
        ->condition('uid', $account->id())
        ->condition('status', 1)
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storageCard->loadMultiple($bricc_card_ids) as $bricc_card_item) {
        $bricc_card_item->set('status', FALSE)->save();
      }

      break;

    case 'user_cancel_reassign':
      // Anonymize categories.
      $storage = \Drupal::entityTypeManager()->getStorage('bricc_category');
      $bricc_category_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storage->loadMultiple($bricc_category_ids) as $bricc_category) {
        $bricc_category->setOwnerId(0)->save();
      }

      // Anonymize card item.
      $storageCard = \Drupal::entityTypeManager()->getStorage('bricc_card_item');
      $bricc_card_ids = $storage->getQuery()
        ->condition('uid', $account->id())
        ->accessCheck(FALSE)
        ->execute();
      foreach ($storageCard->loadMultiple($bricc_card_ids) as $bricc_card_item) {
        $bricc_card_item->setOwnerId(0)->save();
      }
      break;
  }
}

/**
 * Implements hook_ENTITY_TYPE_predelete() for user entities.
 */
function bricc_user_predelete(UserInterface $account): void {
  // Delete categories that belong to this account.
  $storage = \Drupal::entityTypeManager()->getStorage('bricc_category');
  $bricc_category_ids = $storage->getQuery()
    ->condition('uid', $account->id())
    ->accessCheck(FALSE)
    ->execute();
  $storage->delete(
    $storage->loadMultiple($bricc_category_ids)
  );
}

/**
 * Implements hook_page_attachments().
 */
function bricc_page_attachments(array &$attachments) {
  if (\Drupal::currentUser()->isAuthenticated()) {
    $attachments['#attached']['library'][] = 'bricc/admin';
  }
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function bricc_form_user_login_form_alter(&$form, FormStateInterface $form_state) {
  $form['#submit'][] = 'bricc_user_login_submit';
  $form['#attached']['library'][] = 'bricc/login';
}

/**
 * Form submission handler for user_login_form().
 *
 * Redirects the user to the dashboard after logging in.
 */
function bricc_user_login_submit(&$form, FormStateInterface $form_state) {
  $url = Url::fromRoute('bricc.admin');

  // Check if a destination was set, probably on an exception controller.
  // @see \Drupal\user\Form\UserLoginForm::submitForm()
  $request = \Drupal::service('request_stack')->getCurrentRequest();
  if (!$request->request->has('destination')) {
    $form_state->setRedirectUrl($url);
  }
  else {
    $request->query->set('destination', $request->request->get('destination'));
  }
}

/**
 * Implements hook_views_data().
 */
function bricc_views_data() {
  $data = [];

  $data['bricc_applicant_remote_data']['table']['group'] = 'bricc_applicant_remote_data';
  $data['bricc_applicant_remote_data']['table']['base'] = [
    'title' => 'BRI CC Applicant remote data',
    'query_id' => 'views_remote_data_query',
  ];

  return $data;
}

/**
 * Implements hook_form_alter().
 */
function bricc_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if ($form_id === 'views_exposed_form') {
    if ($form['#id'] === 'views-exposed-form-applicant-page-1' ||
        $form['#id'] === 'views-exposed-form-applicant-page-2') {
      $form = array_merge([
        'filtering_type' => [
          '#type' => 'select',
          '#title' => t('Filter type'),
          '#options' => [
            'date' => t('Date'),
            'name' => t('Name'),
          ],
          '#default_value' => 'date',
        ],
      ], $form);

      // Jenis kartu to use dropdown
      $card_items = \Drupal::entityTypeManager()->getStorage('bricc_card_item')->loadByProperties([
        'status' => 1,
      ]);
      $option_jenis_kartu = ['' => 'All'];
      /** @var \Drupal\bricc\Entity\BriccCardItem $card_item */
      foreach ($card_items as $card_item) {
        if (!$card_item->get('field_idcardtype')->isEmpty()) {
          $key = $card_item->get('field_idcardtype')->value;
          $label = $card_item->label();
          $option_jenis_kartu[$key] = $label;
        }
      }
      $form['jeniskartu']['#type'] = 'select';
      $form['jeniskartu']['#options'] = $option_jenis_kartu;
      unset($form['jeniskartu']['#size']);

      // Edit field to be type date
      $field_date = [
        'startdate', 'enddate', 'tgllahir',
      ];
      foreach ($field_date as $field) {
        $form[$field]['#type']= 'date';
      }

      $export_route = 'view.applicant.data_export_1';
      if ($form['#id'] === 'views-exposed-form-applicant-page-2') {
        $export_route = 'view.applicant.data_export_2';
      }

      $current_request = \Drupal::service('request_stack')->getCurrentRequest();
      $current_query_string = $current_request->query->all();
      if (!empty($current_query_string)) {
        $form['actions']['export'] = [
          '#type' => 'link',
          '#title' => t('Export'),
          '#url' => Url::fromRoute($export_route, [], [
            'query' => $current_query_string,
          ]),
          '#attributes' => [
            'class' => ['button js-form-submit form-submit'],
          ],
          '#weight' => 10,
        ];
      }
    }
  }
  elseif ($form_id === 'bricc_card_item_add_form' || $form_id === 'bricc_card_item_edit_form') {
    $query = \Drupal::entityTypeManager()->getStorage('bricc_card_item')->getQuery();
    $entity_ids = $query->accessCheck(FALSE)->execute();
    $exclude = [];
    if (!empty($entity_ids)) {
      // Load the entities based on the IDs found.
      $entities = BriccCardItem::loadMultiple($entity_ids);
      foreach ($entities as $entity) {
        // Get the card_link field value.
        if (!$entity->get('field_idcardtype')->isEmpty()) {
          $exclude[] = $entity->get('field_idcardtype')->value;
        }
      }
    }

    // If this is edit form, remove current value from exclude
    if ($form_id === 'bricc_card_item_edit_form') {
      $bricc_card_item = $form_state->getFormObject()->getEntity();
      if ($bricc_card_item instanceof BriccCardItem) {
        if ($bricc_card_item->hasField('field_idcardtype')) {
          if (!$bricc_card_item->get('field_idcardtype')->isEmpty()) {
            $field_idcardtype = $bricc_card_item->get('field_idcardtype')->value;
            $key = array_search($field_idcardtype, $exclude);
            if ($key !== FALSE) {
              unset($exclude[$key]);
            }
          }
        }
      }
    }

    // Card type
    $card_type_options = \Drupal::service('bricc.parser_remote_data')->formattedCardType($exclude);

    $form['select_idcardtype'] = [
      '#type' => 'select',
      '#title' => t('Card link'),
      '#options' => $card_type_options,
      '#default_value' => $form['field_idcardtype']['widget'][0]['value']['#default_value'], // Set the default value if needed.
      '#description' => t('Connect this data with BRI Card Type'),
      '#weight' => 0,
//      '#required' => TRUE,
    ];
    $form['field_idcardtype']['widget'][0]['value']['#attributes']['readonly'] = TRUE;
    $form['#validate'][] = 'bricc_card_item_form_validate';
  }
  elseif ($form_id === 'node_card_detail_form' || $form_id === 'node_card_detail_edit_form') {
    $form['#validate'][] = 'bricc_card_detail_page_form_validate';

    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = '_bricc_card_item_submit';
      }
    }
  }
}

function _bricc_card_item_submit($form, \Drupal\Core\Form\FormStateInterface $form_state) {
  $nid = 3;
  $config_bricc = ConfigPages::config('bri_cc');
  if ($config_bricc instanceof ConfigPages) {
    if (!$config_bricc->get('field_id_jenis_kartu_kredit')->isEmpty()) {
      $nid = $config_bricc->get('field_id_jenis_kartu_kredit')->value;
    }
  }

  $node = Node::load($nid);
  if ($node) {
    // Invalidate the cache for this specific node.
    Cache::invalidateTags($node->getCacheTags());
  }
}

function bricc_card_item_form_validate(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($form_state->hasValue('field_idcardtype')) {
    $field_idcardtype = $form_state->getValue('field_idcardtype');
    if (isset($field_idcardtype[0]['value'])) {
      $node = $form_state->getFormObject()->getEntity();

      // Check is there a card item that already connect with this BRI card
      $query = \Drupal::entityQuery('bricc_card_item')
        ->accessCheck(FALSE)
        ->condition('field_idcardtype', $field_idcardtype[0]['value']);

      // If update mode
      if (!$node->isNew()) {
        $current_nid = $node->id();
        $query->condition('id', $current_nid, '<>');
      }

      // Execute the query to get the node IDs.
      $nids = $query->execute();

      if (count($nids) > 0) {
        $form_state->setErrorByName('field_idcardtype', t('There are already Card Item link to this card.'));
      }
    }
  }
}

function bricc_card_detail_page_form_validate(array &$form, \Drupal\Core\Form\FormStateInterface $form_state) {
  if ($form_state->hasValue('field_card_item')) {
    $field_card_item = $form_state->getValue('field_card_item');
    if (isset($field_card_item[0]['target_id'])) {
      $node = $form_state->getFormObject()->getEntity();

      // Check is there a card detail page with the same target_id
      $nodes = \Drupal::entityTypeManager()->getStorage('node')->loadByProperties([
        'field_card_item' => $field_card_item[0]['target_id'],
      ]);

      // Create the entity query.
      $query = \Drupal::entityQuery('node')
        ->accessCheck(FALSE)
        ->condition('type', 'card_detail')
        ->condition('field_card_item', $field_card_item[0]['target_id']);

      // If update mode
      if (!$node->isNew()) {
        $current_nid = $node->id();
        $query->condition('nid', $current_nid, '<>');
      }

      // Execute the query to get the node IDs.
      $nids = $query->execute();

      if (count($nids) > 0) {
        $form_state->setErrorByName('field_card_item', t('The are already Card detail page for this Card item.'));
      }
    }
  }
}

function bricc_rest_resource_alter(&$definitions): void {
  if (!empty($definitions['rest_menu_item'])) {
    $definitions['rest_menu_item']['uri_paths']['canonical'] = '/bricc-api/menu-items/{menu_name}';
  }
}

function bricc_rest_menu_items_output_alter(array &$menu_items) {
  _bricc_handle_rest_menu_items_icon($menu_items);
}

function _bricc_handle_rest_menu_items_icon(&$menu_items) {
  foreach ($menu_items as &$menu_item) {
    if (isset($menu_item['field_image'])) {
      $media = $menu_item['field_image'];

      if (!$media instanceof Media) {
        $media = Media::load($menu_item['field_image']);
      }

      if ($media instanceof Media) {
        if (!$media->get('field_media_image')->isEmpty()) {
          $file_id = $media->get('field_media_image')->target_id;
          $file = File::load($file_id);
          $file_uri = $file->getFileUri();
          $url = \Drupal::service('file_url_generator')->generateString($file_uri);
          $menu_item['icon'] = $url;
        }
      }
    }

    // If menu item is linked to node
    if (str_starts_with($menu_item['uri'], 'node')) {
      $paths = explode('/', $menu_item['uri']);
      if (isset($paths[1]) && is_numeric($paths[1])) {
        $menu_item['nid'] = $paths[1];
      }
    }

    if (isset($menu_item['below'])) {
      _bricc_handle_rest_menu_items_icon($menu_item['below']);
    }
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function bricc_preprocess_html(&$variables) {
  $roles = \Drupal::currentUser()->getRoles();
  if (count($roles) > 0) {
    $role_classes = implode(' ', $roles);
    $variables['attributes']['class'][] = $role_classes;
  }

}

/**
 * Implements hook_entity_delete().
 */
function bricc_entity_delete(\Drupal\Core\Entity\EntityInterface $entity) {
  if ($entity->getEntityTypeId() === 'bricc_card_item') {
    $cache_tags = $entity->getCacheTags();

    if ($entity->hasField('field_category')) {
      if (!$entity->get('field_category')->isEmpty()) {
        $field_category = $entity->get('field_category')->referencedEntities()[0];
        if ($field_category instanceof BriccCategory) {
          $category_cache_tags = $field_category->getCacheTags();
          $cache_tags = array_merge($category_cache_tags, $cache_tags);
        }
      }
    }

    \Drupal::service('cache_tags.invalidator')->invalidateTags($cache_tags);
  }
}
