<?php

//function custom_url_prefix_user_login($account) {
  // Custom URL to redirect after login.
//  $custom_redirect_url = $_ENV['APP_PREFIX']; // Change this URL as needed.
//
//  // Redirect user to the custom URL.
//  $response = new \Symfony\Component\HttpFoundation\RedirectResponse($custom_redirect_url);
//  $response->send();
//}

/**
 * Implements hook_js_settings_alter().
 */
function custom_url_prefix_js_settings_alter(
  array &$settings,
  \Drupal\Core\Asset\AttachedAssetsInterface $assets
) {
  $settings['path']['baseUrl'] = rtrim($_ENV['APP_PREFIX'], '/') . '/';
}
