version: '3'

services:
  app:
    build: 
      context: .
      dockerfile: DockerfileApp
    volumes:
      - ../../bri-web-drupal:/workspaces:cached
    command: sleep infinity
    network_mode: host
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ../../bri-web-drupal:/workspaces:cached
    network_mode: service:app